# Generated by Django 2.2.6 on 2020-05-22 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=50, verbose_name='自定义id')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='图片文件')),
                ('txt', models.TextField(verbose_name='文本')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='标记时间')),
            ],
            options={
                'verbose_name': '待标注数据',
                'verbose_name_plural': '待标注数据',
            },
        ),
        migrations.CreateModel(
            name='LabelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='大类标签')),
            ],
            options={
                'verbose_name': '大类标签',
                'verbose_name_plural': '大类标签',
            },
        ),
        migrations.CreateModel(
            name='LabelSubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='子类标签')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '子类标签',
                'verbose_name_plural': '子类标签',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('has_finished', models.BooleanField(default=False, verbose_name='是否完成')),
                ('has_distributed', models.BooleanField(default=False, verbose_name='是否分配')),
                ('max_label_nums', models.IntegerField(default=3, verbose_name='最大标注数目')),
            ],
            options={
                'verbose_name': '标注任务',
                'verbose_name_plural': '标注任务',
            },
        ),
    ]
