# Generated by Django 2.2.6 on 2020-05-22 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='labelsubclass',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.LabelClass', verbose_name='父类'),
        ),
        migrations.AddField(
            model_name='labelclass',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='任务'),
        ),
    ]
