# Generated by Django 2.2.6 on 2020-05-27 13:33

from django.db import migrations
import django.utils.timezone
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200522_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='image',
            field=stdimage.models.StdImageField(default=django.utils.timezone.now, max_length=50, upload_to=stdimage.utils.UploadToUUID(path='media/2020/05'), verbose_name='图片文件'),
            preserve_default=False,
        ),
    ]
