# Generated by Django 2.2.6 on 2020-05-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltask',
            name='data_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.DataItem', verbose_name='数据'),
        ),
    ]
