# Generated by Django 2.2.6 on 2020-05-22 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('label', '0002_labeltask_data_item'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltask',
            name='tagger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='标注者'),
        ),
        migrations.AddField(
            model_name='labelresult',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.LabelSubClass', verbose_name='标注结果'),
        ),
        migrations.AddField(
            model_name='labelresult',
            name='tagger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='标注者'),
        ),
        migrations.AddField(
            model_name='labelresult',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='任务'),
        ),
    ]
